### PR TITLE
Refactor ROS package structure

### PR DESCRIPTION
**Pull request by emilyxzhou**
Moved ROS nodes to a `/nodes` directory in each ROS package. No code changes aside from `face_service.py` to ensure that the resource path was still valid.

### CODE REVIEW

**Comment by chrismbirmingham** [comment]
Hi Emily, great work! Can you make sure to run the rostests before I do my review? I believe there is an issue with at least the face package expression jsons.

**Comment by emilyxzhou** [comment]
I moved `face_service.py` back to `src` because the mouth and eyes service were being imported from a different script. 
As for the rostests, I get the same timeout error on both this branch and `develop`, so I'm not sure if my changes broke them:

image

Can you let me know if I'm missing a setup step that's causing this error? If it turns out that this error wasn't caused by my package refactoring, I can open a separate issue for it.

**Comment by chrismbirmingham** [comment]
> I moved `face_service.py` back to `src` because the mouth and eyes service were being imported from a different script.
> As for the rostests, I get the same timeout error on both this branch and `develop`, so I'm not sure if my changes broke them:
> 
> image
> 
> Can you let me know if I'm missing a setup step that's causing this error? If it turns out that this error wasn't caused by my package refactoring, I can open a separate issue for it.

This is a known issue for rostest of web related packages. The current setup requires you to open a web browser and follow the link in the terminal before the test can actually run. This should be documented though I don't believe it is. If you don't open the link the test will timeout.

**Comment by emilyxzhou** [comment]
I noticed that the `test_w2l_input` param in wsl.test needs to be changed to `hello.wav` for that to pass; the rostests look good now.

**Review by chrismbirmingham — APPROVED** [review]

**Pull request merged**
