### PR TITLE
Merging the splitted face services: eyes and mouth

### PR DESCRIPTION
**Pull request by micolspitale93**
I still have to update the README for the face.  It will allow any user to test any expression, action unit, viseme, or gaze direction they want to following the input data required structure of each request. I haven't done it yet because I know @RMichaelSwan is working on documentation and READMEs.
Should I update it in the doc-update branch? Or should I wait for merging and then edit it in the develop branch?

### CODE REVIEW

**Comment by RMichaelSwan** [comment]
> I still have to update the README for the face. It will allow any user to test any expression, action unit, viseme, or gaze direction they want to following the input data required structure of each request. I haven't done it yet because I know @RMichaelSwan is working on documentation and READMEs.
> Should I update it in the doc-update branch? Or should I wait for merging and then edit it in the develop branch?

Probably the easiest approach would be to merge the doc branch (e.g. make sure feature/doc-update is a local branch and then do `git merge feature/doc-update`) into this one and then work from there.

**Comment by micolspitale93** [comment]
I have finally done with the cordial face ( I hope:)). I have split the services into: Mouth, Eyes, and Nose.
All three services can DO facial expressions, and action units. In addition, the Mouth is responsible for the visemes, and the Eyes for the gaze. 
To data, there is no any prioritization, the testing includes only sequential commands. 
For managing the prioritization, we have to restructure the JS. 
In the [README](https://github.com/interaction-lab/HARMONI/tree/feature/cordialface-request/harmoni_actuators/harmoni_face#readme) you will find all the instructions. If you have any doubts, let me know.

**Comment by micolspitale93** [comment]
I have pushed the updates for the harmoni_gesture README in this branch instead of the devel branch. 
If you want you can check it as well, when you are reviewing this pull request.

**Comment by chrismbirmingham** [comment]
Relevant commits have been cherry picked to avoid conflict with the docs. Closing this branch/request

**Pull request closed without merging**
