### PR TITLE
Remove test:= true

### LINKED ISSUE #45: Remove test:=true references
Currently our dockerfile setup_script has a number of aliases for our old way of testing. These should be updated to reflect current rostest usage. In general anything that mentions the rosparam `test` (usually `test:=true`) should be updated/fixed.
https://github.com/interaction-lab/HARMONI/blob/609f52a21000d0884ac1654464dbc525e34d0145/dockerfiles/config/setup_script.sh#L24

### PR DESCRIPTION
**Pull request by emdg05**

### CODE REVIEW

**Comment by chrismbirmingham** [comment]
We appear to still have old references to test in the harmoni_decision package which need to be refactored. @micolspitale93 have you updated harmoni_decision to ensure the launcher.py works correctly with the new launch files?

**Comment by micolspitale93** [comment]
> We appear to still have old references to test in the harmoni_decision package which need to be refactored. @micolspitale93 have you updated harmoni_decision to ensure the launcher.py works correctly with the new launch files?




No I haven't. I think that I need to fix some line commands. I'll work on it during this week.

**Comment by micolspitale93** [comment]
I have fixed the launcher for automatically launching harmoni services.

**Review by micolspitale93 — APPROVED** [review]
The setup alias has been correctly updated. Now, also the automatic launchins is working.

**Review by chrismbirmingham — APPROVED** [review]

**Pull request merged**
